name: serveme
description: Backend server framework designed for a quick development of modular WebSocket based server applications with MongoDB integration.
version: 1.1.3
homepage: https://github.com/sourcecaster/serveme
repository: https://github.com/sourcecaster/serveme
issue_tracker: https://github.com/sourcecaster/serveme/issues
documentation: https://github.com/sourcecaster/serveme
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  mongo_dart: ^0.7.0+2
  yaml: ^3.1.0
  connectme: ^2.0.2
  packme: ^1.1.5
dev_dependencies:
  test: ^1.17.11