name: remote_control_server
description: A terminal like server to your Dart App
version: 0.0.2
homepage: https://github.com/ranierjardim/flutter_remote_control/remote_control_server

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  remote_control_core:
    path: ../remote_control_core
  get_server: ^1.1.1
  conduit: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
