name: remote_control_core
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/ranierjardim/flutter_remote_control/core

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  web_socket_channel: ^2.2.0
  get_server: ^1.1.1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
