name: remote_control_test
description: A command-line application to test the RemoteControl and RemoteControlServer together.
version: 1.0.0
# homepage: https://www.example.com
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  remote_control:
    path: ../remote_control
  remote_control_server:
    path: ../remote_control_server

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
