name: remote_control_core
description: A terminal like server to your Dart App
version: 0.0.2
homepage: https://github.com/ranierjardim/flutter_remote_control/remote_control_core

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
